AZURE_CLU_ENDPOINT = "https://languagetajamar.cognitiveservices.azure.com/language/:analyze-conversations?api-version=2022-10-01-preview"
AZURE_CLU_KEY = "G52j0lmBhH5dGozDyabrNW70PyaZriRSvzlpXT5lyFUtLS0RdAsFJQQJ99BAACYeBjFXJ3w3AAAaACOG70JU"
CLU_PROJECT_NAME = "FinanceAssistant"
CLU_DEPLOYMENT_NAME = "production"
